import Head from 'next/head';
import Image from 'next/image';

import HeroBanner from './components/HeroBanner';

import styles from '../styles/Home.module.css'

export default function Home() {
	return (
		<div id="wrapper">
			<Head>
				<title>Web UI Exports</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HeroBanner />
		</div>
	)
}
