import Head from 'next/head';
import Image from 'next/image';

import HeroBanner from './components/HeroBanner';
import OurServices from './components/OurServices';
import About from './components/About';
import Available from './components/Available';

import styles from '../styles/Home.module.css'

export default function Home() {
	return (
		<>
			<Head>
				<title>Web UI Exports</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HeroBanner />
			<OurServices />
			<About />
			<Available />
		</>
	)
}
